on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 0,3'  # At 00:00 on Sunday and Wednesday
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1

      - uses: actions/setup-node@v2
        with:
          node-version: '15'

      - run: npm install

      - run: npm run build
        env:
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}

      - uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: public